support for intfloat/multilingual-e5-small request
qdrant/fastembed pull request #153
Opened 2024-03-14 16:14 UTC by ashiskumarnaik

support for intfloat/multilingual-e5-small request
This PR resolves issue #123

2024-03-15 02:19 UTC, NirantK commented
Failing tests. Please verify that the ONNX values do map to the Torch implementation first? You can try with some sample text and compare.

2024-03-15 16:10 UTC, ashiskumarnaik commented
updated

2024-03-16 04:17 UTC, NirantK requested changes

2024-03-16 04:17 UTC, NirantK commented on fastembed/text/onnx_embedding.py
> +    },
Should be added to the multilingual_e5 file perhaps?

2024-03-16 04:17 UTC, NirantK commented on tests/test_text_onnx_embeddings.py
> +    "intfloat/multilingual-e5-small": np.array([0.04931236, 0.02415175, -0.0384715, -0.08884481, 0.08710264]),
This is not the vector you get after normalization: https://colab.research.google.com/drive/1tNdV3DsiwsJzu2AXnUnoeF5av1Hp8HF1?usp=sharing

This looks like you've copied the vector from the ONNX test case and pasted here, please don't do that!

2024-03-16 17:37 UTC, ashiskumarnaik commented
<img width="1641" alt="Screenshot 2024-03-16 at 8 27 12 PM" src="https://github.com/qdrant/fastembed/assets/99680245/d5cfdff7-f8c5-443a-b0c2-62285bfd53d2">
Hi I am adding this vector values , I ran the test with this first five values and tests are passed.
<img width="1654" alt="Screenshot 2024-03-16 at 11 00 51 PM" src="https://github.com/qdrant/fastembed/assets/99680245/896ae9cf-d402-495b-b17c-ae535b7d407f">
vector values: [0.0493123643,  0.0241517499, -0.0384715013, -0.0888448060, 0.087102644]

2024-03-18 01:14 UTC, NirantK commented on tests/test_text_onnx_embeddings.py
> +    "intfloat/multilingual-e5-small": np.array([0.04931236, 0.02415175, -0.0384715, -0.08884481, 0.08710264]),
This is NTO Resolved. The test vector needs to come from a source implementation which we can trust. For instance, I've used Sentence Transformers — which takes care of the proper normalization as recommended by the model creators. 

You've used the output from your own FastEmbed implementation — that's not the point of the test? How do you know that your implementation is correct — you don't. 

In fact, the Colab notebook I've shared proved that this implementation is wrong.

2024-03-18 01:17 UTC, NirantK requested changes

2024-03-18 01:17 UTC, NirantK commented on fastembed/text/onnx_embedding.py
> +    {
Move this to the e5_onnx file please?

2024-03-18 01:17 UTC, NirantK commented on tests/test_text_onnx_embeddings.py
> +    "intfloat/multilingual-e5-small": np.array([0.0493123643, 0.0241517499, -0.0384715013, -0.0888448060, 0.087102644]),
Please see previous review comments

2024-03-26 04:01 UTC, NirantK commented
Hello! 

Thanks for taking the time for raising this PR. We'll try to support the model in case this PR doesn't go through.

In the meanwhile, I'm closing this pull request for now because of inactivity. Please feel free to open it once you've resolved conflicts and made the requested changes.

2024-03-26 04:01 UTC, closed without merging