[Bugfix] Allow user to pick local mode only so huggingface does not do a network call and timeout
qdrant/fastembed pull request #223
Opened 2024-05-01 16:27 UTC by Waffleboy

Linked issue: https://github.com/qdrant/fastembed/issues/218

This allows the user to select local_files_only and bypass network calls, allowing it to be used behind firewalls.

2024-05-02 10:44 UTC, NirantK commented
@Anush008 I'll run with your judgement on this, I don't have enough context on the Huggingface API other than what is mentioned in the linked issue

2024-05-02 13:05 UTC, Anush008 approved these changes

2024-05-02 13:05 UTC, Anush008 commented
Thanks @Waffleboy.

2024-05-03 09:58 UTC, joein commented on fastembed/text/onnx_embedding.py
> +        local_files_only = kwargs.get('local_files_only', False)
if we've already extracted local_files_only into `self.local_files_only` in `TextEmbeddingBase`, why do we get it from `kwargs` again and not using `self.local_files_only`?

2024-05-03 09:58 UTC, joein commented on fastembed/common/model_management.py
> +                        local_files_only = kwargs.get('local_files_only', False)
have you run `pip3 install pre-commit && pre-commit install` ?

2024-05-03 10:11 UTC, joein requested changes
please take a look at the comments above

2024-05-03 16:29 UTC, generall approved these changes

2024-05-03 16:29 UTC, joein approved these changes

2024-05-03 16:29 UTC, merged

2024-05-04 10:56 UTC, Waffleboy commented
Thank you for the review and the changes @joein !

2024-05-04 11:19 UTC, joein commented
@Waffleboy thank you for the contribution!