MiniLM fix
qdrant/fastembed pull request #275
Opened 2024-06-13 23:45 UTC by I8dNLo

MiniLM fix.
Now it uses official implementation and pooling from SM repo

2024-06-14 10:52 UTC, joein requested changes
It's better not to mix style refactoring + actual code changes in one PR, because it becomes more difficult to review.
It might be ok to combine them in one PR once the code changes are approved

2024-06-14 10:52 UTC, joein commented on fastembed/text/mini_lm_embedding.py
> +    def mean_pooling(self, model_output, attention_mask):
type hints

2024-06-14 10:52 UTC, joein commented on fastembed/text/mini_lm_embedding.py
> +        cache_dir: str,
kwargs are missing

2024-06-14 10:52 UTC, joein commented on fastembed/text/mini_lm_embedding.py
> +            model_name=model_name, cache_dir=cache_dir, threads=1
kwargs are missing

2024-06-14 10:52 UTC, joein commented on tests/test_text_onnx_embeddings.py
> +        [0.0259, 0.0058, 0.0114, 0.0380, -0.0233]
canonical values should be updated

2024-06-14 13:19 UTC, joein approved these changes

2024-06-14 13:42 UTC, merged

2024-06-24 17:08 UTC, michaelfeil commented
Awesome! @I8dNLo