Tf-idf fix:
qdrant/fastembed pull request #339
Opened 2024-09-09 14:56 UTC by I8dNLo

Remove punctuation properly + lowercase
Average recall 0.83 -> 0.88

2024-09-10 14:26 UTC, joein commented on fastembed/sparse/bm25.py
> +        self.token_accum: int = 0
redundant?

2024-09-10 17:59 UTC, I8dNLo commented on fastembed/sparse/bm25.py
> +        self.token_accum: int = 0
Sure

2024-09-23 09:24 UTC, joein requested changes

2024-09-23 09:24 UTC, joein commented on fastembed/common/utils.py
> +def get_all_punctuation():
type annotation

2024-09-23 09:24 UTC, joein commented on fastembed/common/utils.py
> +def replace_punctuation(text, punctuation):
type annotation

2024-09-23 09:24 UTC, joein commented on fastembed/sparse/bm25.py
> +def remove_non_alphanumeric(text):
docstring

2024-09-23 09:24 UTC, joein commented on fastembed/common/utils.py
> +def replace_punctuation(text, punctuation):
defined, but not used?

2024-09-23 09:24 UTC, joein commented on fastembed/sparse/utils/tokenizer.py
> +    def __init__(self):
redundant method

2024-09-23 09:24 UTC, joein commented on fastembed/sparse/utils/tokenizer.py
> +    def tokenize(text: str):
return type annotation is missing

2024-09-23 09:24 UTC, joein commented on fastembed/sparse/bm25.py
> +def remove_non_alphanumeric(text):
maybe it should be in utils as well? 🤔

2024-09-24 10:16 UTC, joein approved these changes

2024-09-24 11:21 UTC, merged